apiVersion: v1
kind: Service
metadata:
  name: website-personal-service
spec:
  selector:
    app: website-personal  # Debe coincidir con la etiqueta en el Deployment
  ports:
    - protocol: TCP
      port: 8080  # El puerto al que se accederá dentro del clúster
      targetPort: 8080  # El puerto en el contenedor
      nodePort: 30080    # El puerto que Minikube usará en la máquina local para acceder al servicio
  type: NodePort  # Exponer el servicio como un NodePort
